---
deployment:
  tasks:
    - export DEPLOYPATH=/home/restok/public_html/test/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH