---
deployment:
  tasks:
    - export DEPLOYPATH=/home/restok/public_html/test/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp css/* $DEPLOYPATH
    - /bin/cp assets/* $DEPLOYPATH
    - /bin/cp js/* $DEPLOYPATH